version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install && npm run install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run start

artifacts:
  files:
    - '**/*'